# Dependabot creates pull requests to keep your dependencies secure and up-to-date.
# Documentation: https://docs.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:

  - package-ecosystem: 'github-actions'
    directory: '/'
    open-pull-requests-limit: 10
    schedule:
      interval: 'weekly'
      day: 'monday'

  - package-ecosystem: "npm"
    directory: "packages/cli"
    schedule:
      interval: 'weekly'
      day: 'monday'

  - package-ecosystem: "npm"
    directory: "packages/common"
    schedule:
      interval: 'weekly'
      day: 'monday'

  - package-ecosystem: "npm"
    directory: "packages/extension-database"
    schedule:
      interval: 'weekly'
      day: 'monday'

  - package-ecosystem: "npm"
    directory: "packages/extension-logger"
    schedule:
      interval: 'weekly'
      day: 'monday'

  - package-ecosystem: "npm"
    directory: "packages/extension-redis"
    schedule:
      interval: 'weekly'
      day: 'monday'

  - package-ecosystem: "npm"
    directory: "packages/extension-sqlite"
    schedule:
      interval: 'weekly'
      day: 'monday'

  - package-ecosystem: "npm"
    directory: "packages/extension-throttle"
    schedule:
      interval: 'weekly'
      day: 'monday'

  - package-ecosystem: "npm"
    directory: "packages/extension-webhook"
    schedule:
      interval: 'weekly'
      day: 'monday'

  - package-ecosystem: "npm"
    directory: "packages/provider"
    schedule:
      interval: 'weekly'
      day: 'monday'

  - package-ecosystem: "npm"
    directory: "packages/server"
    schedule:
      interval: 'weekly'
      day: 'monday'

  - package-ecosystem: "npm"
    directory: "packages/transformer"
    schedule:
      interval: 'weekly'
      day: 'monday'
