name: Verify

env:
  NODE_VERSION: 24
  PNPM_VERSION: 11.2.2

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main
      - next
      - release/*
  pull_request:
    branches:
      - main
      - next
      - release/*

jobs:
  install-node-dependencies:
    name: Install node dependencies
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v7

      - uses: pnpm/action-setup@v7

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v7
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

  build-packages:
    name: Build packages
    runs-on: ubuntu-latest
    needs: install-node-dependencies
    timeout-minutes: 20

    steps:
      - uses: actions/checkout@v7

      - uses: pnpm/action-setup@v7

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v7
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build packages
        run: pnpm build:packages

      - name: Check package exports
        run: node scripts/check-package-exports.mjs

  check-linting-formatting:
    name: Check linting & formatting
    runs-on: ubuntu-latest
    needs: install-node-dependencies
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v7

      - uses: pnpm/action-setup@v7

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v7
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run linting and formatting checks
        run: pnpm check

  run-unit-tests:
    name: Run unit tests
    runs-on: ubuntu-latest
    needs: install-node-dependencies
    timeout-minutes: 20

    services:
      redis:
        image: redis
        ports:
          - 6379/tcp
        options: --entrypoint redis-server

    steps:
      - uses: actions/checkout@v7

      - uses: pnpm/action-setup@v7

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v7
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run unit tests
        run: pnpm test
        env:
          REDIS_HOST: localhost
          REDIS_PORT: ${{ job.services.redis.ports[6379] }}
