//! Golden-vector conformance tests.
//!
//! `fixtures/frames.json` is generated by the REAL TypeScript
//! implementation (`tests/conformance/generate-protocol-fixtures.mts` at the
//! repo root, driving `OutgoingMessage`, `@hocuspocus/common`, lib0,
//! y-protocols and yjs). Every fixture must decode, its semantic content
//! must match the recorded expectations, and re-encoding must be byte-exact
//! wherever the encoding is deterministic.

use base64::engine::general_purpose::STANDARD as BASE64;
use base64::Engine;
use bytes::Bytes;
use serde::Deserialize;

use hocuspocus_protocol::{
    redis, AuthInbound, AuthOutbound, AwarenessUpdate, Frame, MessageType, Reader, Scope,
    SyncMessage, Writer,
};

#[derive(Debug, Deserialize)]
struct FixtureFile {
    fixtures: Vec<Fixture>,
}

#[derive(Debug, Deserialize)]
struct Fixture {
    name: String,
    kind: String,
    base64: String,
    expect: serde_json::Value,
}

fn fixtures() -> Vec<Fixture> {
    let raw = include_str!("fixtures/frames.json");
    serde_json::from_str::<FixtureFile>(raw)
        .expect("fixtures/frames.json parses")
        .fixtures
}

fn bytes_of(fixture: &Fixture) -> Bytes {
    Bytes::from(BASE64.decode(&fixture.base64).expect("valid base64"))
}

fn expect_bytes(expect: &serde_json::Value, key: &str) -> Bytes {
    Bytes::from(
        BASE64
            .decode(expect[key].as_str().expect("base64 field"))
            .expect("valid base64"),
    )
}

#[test]
fn all_fixtures_are_covered() {
    // If the generator grows a new kind, this test must grow with it.
    for fixture in fixtures() {
        assert!(
            matches!(
                fixture.kind.as_str(),
                "envelope" | "bare" | "awareness_update" | "redis" | "yjs_update" | "state_vector"
            ),
            "unknown fixture kind {} ({})",
            fixture.kind,
            fixture.name
        );
    }
}

#[test]
fn envelopes_decode_and_reencode_byte_exact() {
    for fixture in fixtures().iter().filter(|f| f.kind == "envelope") {
        let original = bytes_of(fixture);
        let envelope = match Frame::decode(original.clone()) {
            Ok(Frame::Message(envelope)) => envelope,
            other => panic!("{}: expected envelope, got {other:?}", fixture.name),
        };

        // Address expectations.
        let expected_address = fixture.expect["address"].as_str().expect("address");
        assert_eq!(&*envelope.address.raw, expected_address, "{}", fixture.name);
        if let Some(name) = fixture.expect.get("document_name").and_then(|v| v.as_str()) {
            assert_eq!(&*envelope.address.document_name, name, "{}", fixture.name);
        }
        if let Some(session) = fixture.expect.get("session_id").and_then(|v| v.as_str()) {
            assert_eq!(
                envelope.address.session_id.as_deref(),
                Some(session),
                "{}",
                fixture.name
            );
        }

        // Message type.
        let expected_type = fixture.expect["message_type"].as_u64().expect("type");
        assert_eq!(
            envelope.kind,
            MessageType::try_from(expected_type).unwrap(),
            "{}",
            fixture.name
        );

        // Byte-exact re-encode: address + type + opaque payload.
        let mut writer = Writer::new();
        writer.write_var_string(&envelope.address.raw);
        writer.write_var_uint(envelope.kind as u64);
        writer.write_raw(&envelope.payload);
        assert_eq!(
            writer.freeze(),
            original,
            "{}: re-encode differs",
            fixture.name
        );

        verify_payload(fixture, &envelope.kind, envelope.payload.clone());
    }
}

fn verify_payload(fixture: &Fixture, kind: &MessageType, payload: Bytes) {
    let mut reader = Reader::new(payload);
    match kind {
        MessageType::Auth => {
            let auth = &fixture.expect["auth"];
            if let Some(token) = auth.get("token").and_then(|v| v.as_str()) {
                // Client → server token frame.
                let decoded = AuthInbound::decode(&mut reader).unwrap();
                let AuthInbound::Token {
                    token: decoded_token,
                    provider_version,
                } = decoded;
                assert_eq!(decoded_token, token, "{}", fixture.name);
                assert_eq!(
                    provider_version.as_deref(),
                    auth["provider_version"].as_str(),
                    "{}",
                    fixture.name
                );
            } else {
                // Server → client.
                let decoded = AuthOutbound::decode(&mut reader).unwrap();
                if let Some(scope) = auth.get("authenticated_scope").and_then(|v| v.as_str()) {
                    assert_eq!(
                        decoded,
                        AuthOutbound::Authenticated {
                            scope: Scope::parse(scope).unwrap()
                        },
                        "{}",
                        fixture.name
                    );
                } else if let Some(reason) = auth
                    .get("permission_denied_reason")
                    .and_then(|v| v.as_str())
                {
                    assert_eq!(
                        decoded,
                        AuthOutbound::PermissionDenied {
                            reason: reason.to_owned()
                        },
                        "{}",
                        fixture.name
                    );
                } else if auth.get("token_request").is_some() {
                    assert_eq!(decoded, AuthOutbound::TokenRequest, "{}", fixture.name);
                } else {
                    panic!("{}: unhandled auth expectation {auth}", fixture.name);
                }
            }
        }
        MessageType::Sync | MessageType::SyncReply => {
            let sync = &fixture.expect["sync"];
            let decoded = SyncMessage::decode(&mut reader).unwrap();
            let expected_body = expect_bytes(sync, "body_base64");
            let (subtype, body) = match &decoded {
                SyncMessage::Step1 { state_vector } => (0, state_vector),
                SyncMessage::Step2 { update } => (1, update),
                SyncMessage::Update { update } => (2, update),
            };
            assert_eq!(
                subtype,
                sync["subtype"].as_u64().unwrap(),
                "{}",
                fixture.name
            );
            assert_eq!(body, &expected_body, "{}", fixture.name);
        }
        MessageType::Stateless | MessageType::BroadcastStateless => {
            assert_eq!(
                reader.read_var_string().unwrap(),
                fixture.expect["stateless_payload"].as_str().unwrap(),
                "{}",
                fixture.name
            );
        }
        MessageType::SyncStatus => {
            let saved = reader.read_var_uint().unwrap() == 1;
            assert_eq!(
                saved,
                fixture.expect["sync_status"].as_bool().unwrap(),
                "{}",
                fixture.name
            );
        }
        MessageType::Close => {
            assert_eq!(
                reader.read_var_string().unwrap(),
                fixture.expect["close_reason"].as_str().unwrap(),
                "{}",
                fixture.name
            );
        }
        MessageType::Awareness => {
            let inner = reader.read_var_bytes().unwrap();
            assert_eq!(
                inner,
                expect_bytes(&fixture.expect, "awareness_inner_base64"),
                "{}",
                fixture.name
            );
            AwarenessUpdate::decode_bytes(inner).unwrap();
        }
        MessageType::QueryAwareness => {
            assert!(!reader.has_content(), "{}", fixture.name);
        }
        other => panic!("{}: unhandled envelope type {other:?}", fixture.name),
    }
}

#[test]
fn bare_ping_pong_frames() {
    for fixture in fixtures().iter().filter(|f| f.kind == "bare") {
        let frame = Frame::decode(bytes_of(fixture)).unwrap();
        if fixture.expect.get("ping").is_some() {
            assert!(matches!(frame, Frame::Ping), "{}", fixture.name);
        } else {
            assert!(matches!(frame, Frame::Pong), "{}", fixture.name);
        }
    }
}

#[test]
fn awareness_updates_decode_and_reencode_byte_exact() {
    for fixture in fixtures().iter().filter(|f| f.kind == "awareness_update") {
        let original = bytes_of(fixture);
        let update = AwarenessUpdate::decode_bytes(original.clone()).unwrap();

        let expected_entries = fixture.expect["entries"].as_array().unwrap();
        assert_eq!(
            update.entries.len(),
            expected_entries.len(),
            "{}",
            fixture.name
        );
        for (entry, expected) in update.entries.iter().zip(expected_entries) {
            assert_eq!(entry.client_id, expected["client_id"].as_u64().unwrap());
            assert_eq!(entry.clock, expected["clock"].as_u64().unwrap());
            // Compare states as JSON values (key order independent).
            let state: serde_json::Value = serde_json::from_str(&entry.state_json).unwrap();
            assert_eq!(&state, &expected["state"], "{}", fixture.name);
            assert_eq!(entry.is_removal(), expected["state"].is_null());
        }

        assert_eq!(
            update.to_bytes(),
            original,
            "{}: re-encode differs",
            fixture.name
        );
    }
}

#[test]
fn redis_frames_decode_and_reencode_byte_exact() {
    for fixture in fixtures().iter().filter(|f| f.kind == "redis") {
        let original = bytes_of(fixture);
        let frame = redis::decode(original.clone()).unwrap();
        assert_eq!(
            frame.identifier,
            fixture.expect["identifier"].as_str().unwrap(),
            "{}",
            fixture.name
        );
        assert_eq!(frame.message, expect_bytes(&fixture.expect, "inner_base64"));
        // The embedded message is itself a valid wire frame.
        assert!(matches!(
            Frame::decode(frame.message.clone()),
            Ok(Frame::Message(_))
        ));
        assert_eq!(
            redis::encode(&frame.identifier, &frame.message).unwrap(),
            original,
            "{}: re-encode differs",
            fixture.name
        );
    }
}

/// The yjs ↔ yrs compatibility check: a full update produced by real yjs
/// must apply cleanly to a yrs document and yield the same content, and the
/// state re-encoded by yrs must round-trip into another yrs document.
#[test]
fn yjs_update_applies_to_yrs() {
    use yrs::updates::decoder::Decode;
    use yrs::{Doc, GetString, Map, ReadTxn, StateVector, Transact, Update};

    for fixture in fixtures().iter().filter(|f| f.kind == "yjs_update") {
        let update_bytes = bytes_of(fixture);
        let doc = Doc::new();
        let text = doc.get_or_insert_text(fixture.expect["text_name"].as_str().unwrap());
        let map = doc.get_or_insert_map(fixture.expect["map_name"].as_str().unwrap());

        {
            let mut txn = doc.transact_mut();
            let update = Update::decode_v1(&update_bytes).expect("yjs update decodes in yrs");
            txn.apply_update(update).expect("yjs update applies in yrs");
        }

        let txn = doc.transact();
        assert_eq!(
            text.get_string(&txn),
            fixture.expect["text_content"].as_str().unwrap(),
            "{}",
            fixture.name
        );
        let value = map
            .get(&txn, fixture.expect["map_key"].as_str().unwrap())
            .expect("map key present");
        assert_eq!(
            value.to_string(&txn),
            fixture.expect["map_value"].to_string(),
            "{}",
            fixture.name
        );

        // Round-trip: yrs-encoded state applies to a fresh yrs doc.
        let reencoded = txn.encode_state_as_update_v1(&StateVector::default());
        drop(txn);
        let doc2 = Doc::new();
        let text2 = doc2.get_or_insert_text(fixture.expect["text_name"].as_str().unwrap());
        {
            let mut txn2 = doc2.transact_mut();
            txn2.apply_update(Update::decode_v1(&reencoded).unwrap())
                .unwrap();
        }
        let txn2 = doc2.transact();
        assert_eq!(
            text2.get_string(&txn2),
            fixture.expect["text_content"].as_str().unwrap(),
            "{}: yrs round-trip",
            fixture.name
        );
    }
}

/// State vectors produced by yjs must decode in yrs.
#[test]
fn yjs_state_vector_decodes_in_yrs() {
    use yrs::updates::decoder::Decode;
    use yrs::StateVector;

    for fixture in fixtures().iter().filter(|f| f.kind == "state_vector") {
        StateVector::decode_v1(&bytes_of(fixture)).expect("yjs state vector decodes in yrs");
    }
}
